name: NPM Installation

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install npm dependencies
        run: npm install

      - name: Generate .env.production
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production
          echo "VITE_AWS_REGION=${{ secrets.VITE_AWS_REGION }}" > .env.production
          echo "VITE_AWS_IDENTITY_POOL_ID=${{ secrets.VITE_AWS_IDENTITY_POOL_ID }}" > .env.production
          echo "VITE_BUCKET_NAME=${{ secrets.VITE_BUCKET_NAME }}" > .env.production
          echo "VITE_ACCESS_KEY_ID=${{ secrets.VITE_ACCESS_KEY_ID }}" > .env.production
          echo "VITE_SECRET_ACCESS_KEY=${{ secrets.VITE_SECRET_ACCESS_KEY }}" > .env.production

      - name: Run build
        run: npm run build -- --mode production

      - name: Clean server build directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            rm -rf /home/ubuntu/jle/*

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: 'build/*'
          target: '/home/ubuntu/jle'
          
      - name: Set permissions for nginx access
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            sudo chmod +x /home/ubuntu
            sudo chown -R www-data:www-data /home/ubuntu/jle
            sudo chmod -R 755 /home/ubuntu/jle