name: NPM Installation

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Clean server build directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            rm -rf /var/www/jle/*

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: 'build/*'
          target: '/var/www/jle'
