name: NPM Installation & Deployment

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 2
  NODE: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}

      - name: Generate .env.production
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env.production
          echo "VITE_AWS_REGION=${{ secrets.VITE_AWS_REGION }}" >> .env.production
          echo "VITE_AWS_IDENTITY_POOL_ID=${{ secrets.VITE_AWS_IDENTITY_POOL_ID }}" >> .env.production
          echo "VITE_BUCKET_NAME=${{ secrets.VITE_BUCKET_NAME }}" >> .env.production
          echo "VITE_ACCESS_KEY_ID=${{ secrets.VITE_ACCESS_KEY_ID }}" >> .env.production
          echo "VITE_SECRET_ACCESS_KEY=${{ secrets.VITE_SECRET_ACCESS_KEY }}" >> .env.production

      - name: Install npm dependencies
        run: npm install

      - name: Build React App
        run: npm run build -- --mode production

      - name: Clean target server build directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/jle/*
            sudo mkdir -p /var/www/jle
            sudo chown -R $USER:$USER /var/www/jle

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: 'build/*'
          target: '/var/www/jle'

      - name: Fix permissions on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            sudo chown -R www-data:www-data /var/www/jle
            sudo chmod -R 755 /var/www/jle
